spring:
  cloud:
    gateway:
      routes:
        - id: rentals-route
          uri: ${RENTALS_ROUTE_URI:http://localhost:8081}
          predicates:
            - Path=/postes/**
          filters:
            - PrefixPath=/api
            - AddResponseHeader=X-Powered-By, Krilya Gateway Service
        - id: user-route
          uri: ${USERS_ROUTE_URI:http://localhost:8082}
          predicates:
            - Path=/users/**
          filters:
            - PrefixPath=/api
            - AddResponseHeader=X-Powered-By, Krilya Gateway Service
      globalcors:
        corsconfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true